development:
  compress:     true
  threadsafe:   true
  namespace:    mor:development
  servers:      localhost:11211
  async:        true
test:
  compress:     true
  threadsafe:   true
  namespace:    mor:test
  servers:      localhost:11211
  async:        true
production:
  compress:     true
  threadsafe:   true
  namespace:    mor
  servers:      <%= ENV['MEMCACHIER_SERVERS'] %>
  password:     <%= ENV['MEMCACHIER_PASSWORD'] %>
  username:     <%= ENV['MEMCACHIER_USERNAME'] %>
  async:        true